// <auto-generated />
using System;
using BibliotecaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaMVC.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20250729011602_CriarTabela")]
    partial class CriarTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaMVC.Models.AlunoModel", b =>
                {
                    b.Property<string>("RA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RA");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("BibliotecaMVC.Models.EmprestimoModel", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlunoRA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRetirada")
                        .HasColumnType("datetime2");

                    b.Property<string>("LivroCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Codigo");

                    b.HasIndex("AlunoRA");

                    b.HasIndex("LivroCodigo");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("BibliotecaMVC.Models.LivroModel", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("BibliotecaMVC.Models.EmprestimoModel", b =>
                {
                    b.HasOne("BibliotecaMVC.Models.AlunoModel", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoRA");

                    b.HasOne("BibliotecaMVC.Models.LivroModel", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Livro");
                });
#pragma warning restore 612, 618
        }
    }
}
